#
# Not the current implementation
#

OPT_DEF_LIST = OPT_DEF ( ',' OPT_DEF )*

OPT_DEF = OPTIONS OPTION_TARGET

OPTIONS = ( SHORT_OPTION | LONG_OPTION ) ( ':' ( SHORT_OPTION | LONG_OPTION ) )*

SHORT_OPTION = OPT_FIRST_CHAR
LONG_OPTION = OPT_FIRST_CHAR OPT_BODY_CHAR+

OPT_FIRST_CHAR = [A-Za-z0-9_]
OPT_BODY_CHAR = [-A-Za-z0-9_]


OPTION_TARGET = ( FLAG | MODE_SWITCH  | ASSIGNMENT | COUNTER )

FLAG = '#' TARGET
MODE_SWITCH = '#' TARGET '=' NAME
ASSIGNMENT = '=' TARGET ( '=' VALUE_RESTRICT )?
COUNTER = '+' NAME

TARGET = ( TARGET_VARIABLE | TARGET_FUNCTION )

TARGET_VARIABLE = NAME
TARGET_FUNCTION = NAME '()'

NAME = [A-Za-z_][A-Za-z0-9_]*


VALUE_RESTRICT = ( NAME_SET | REG_EX | GLOB | INT_RANGE )

NAME_SET = NAME ( '|' NAME )+

REG_EX =  'R' 'i'? '=' STRING
GLOB   =  'G' 'i'? '=' STRING
INT_RANGE  =  NUMBER '<' NUMBER

NUMBER = [0-9]+













