= parseargs(1)
:doctype: manpage
:mansource:  parseargs {manversion}
:manmanual:  Parseargs Manual
:manversion: {pa_version}
:manpurpose: command line option parser for shell scripts

== NAME
parseargs - command line option parser for shell scripts

IMPORTANT: This man page is work on progress!


== SYNOPSIS
*parseargs* [options] \-- script-arguments


== DESCRIPTION
Parseargs parses the command line option and arguments of a shell script based on a given option-definition.
The option-definition defines the options supported by the script and the shell variables to set when a corresponding option is found on the command line.
The code to set the variables is printed an can be evaluated using the shells `eval` builtin.

Typical usage in a script:

    eval "$(parseargs -o '....' -- "$@")"

== OPTIONS

*-o, --options* OPTION-DEFINITION::
Define the options supported by the shell script.
See <<OD,*OPTION DEFINITION*>> below.

*-n, --name* NAME::
Name of shell script.
Used as prefix for error messages.
If not given, used `parseargs`.

*-a, --arg-callback* SHELL-FUNCTION::
Call function SHELL-FUNCTION to report program arguments.
When used `$#` will always be 0 after parseargs call.

*-e, --error-callback* SHELL-FUNCTION
When an error is detected, call the given function before exiting the script.
The function can be used to echo additional hints (like "Try ... --help") or change the exit code.

*-r, --remainder* SHELL-VARIABLE::
Collect all parameter behind a '--' in the named array.
ONLY SUPPORTED WITH --shell `bash`, `ksh`, or `zsh`.

*-p, --posix*::
Behave like recommended by POSIX and stop option processing on first none-option.

*-i, --init-vars*::
Initialize all variables with '', except for counting variables, as they are always initialized with 0

*-l, --local-vars*::
Create local variables. __Not supported with --shell sh__

*-h, --help-opt*::
Enable support for --help as script option.
The calling script must provide the function `show_help` that displays the help text.

*-v, --version-opt*::
Enable support for --version as script options.
The calling script must provide the function `show_version` that displays the version text.

*-s, --shell* SHELL::
Produce code for named shell. Supported: `bash`, `ksh`, `zsh`, `sh`. Default: `sh`

*--help*::
Print help.

*--version*::
Print the Parseargs version.


[[OD]]
== OPTION DEFINITION

A option definition is a comma-separated list of definitions.
The simple single definitions is:

    <option-names><option-type><option-variable>

option-names::
The option-names consist of one or more option chars or strings separated by colons.
A single char defines an option that is given with a leading dash (e.g. `l` for `-l`). +
Allowed chars:  `A-Za-z0-9!"$&'()*,./;<>?@[]^_{|}~` and with backslash escape: `#%+:=\`.
Some of this characters need a backslash escape on the command line.
+
A string defines a long option that is given with two leading dashes (e.g. `long` for `--long`).
String may consist of the same chars as the short option. Additional the minus (`-`) is allowed, if it is not the first char.

option-type::
Following option types are supported:

`#`:::
 Flag - Variable is set to "`true`" if option given.
`=`:::
Assignment - Option needs additional option-argument.
`+`:::
Counting variable - Occurrences of option are counted. `-v` results in 1, `-vv` results in 2 ...


option-variable::
Name of the variable to set for the option. This must be a valid shell variable or function name.
If the name ends with `()` the name identifies a function to call to set the value (see <<OCB, *OPTION CALLBACK FUNCTIONS*>> below). +
If the option is a flag and variable name contains a `=` (like: "`action=commit`"), the value after the equal sign is assigned to the variable if the option is given. +
This way the variable name might be used multiple times with different values (see <<MSO, *Mode Switch Options*>>).
+
Variable names can be prefixed with a `*` (see <<RQ, REQUIRED OPTIONS>>) or a `?` (see <<HP, OWN HELP OPTIONS>>)

=== Option Definition Examples

l#long::
Defines the option `-l` to set the variable `long`.

l:long#long::
Defines the options `-l` and `--long` to set the variable `long`.

o:out-file=outfile::
Defines the options `-o` and `--out-file` that need an additional argument.
This argument is assigned to the variable `outfile`.

c#mode=copy,m#mode=move::
Defines the options `-c` and `-m`.
With `-c` the variable `mode` gets the value "copy" assigned, with `-m` the value "move".
`-c` and `-m` are mutual exclusive.

v+verbosity::
Defines `-v` as a counting option. The occurrences of `-v` on the command line is counted and assigned to the variable `verbosity`.

=== Long Options and Values

Long options get their value from the next argument on the command line or directly appended with a `=`.

    --out-file result.txt
    --out-file=result.txt

Also flags with a long option can get a value, but then only the variant with the `=` is supported:

    --debug=true
    --debug=false

    --verbosity=4

For flags the values `true` and `yes` are handled as boolean true and `false` or `no` as boolean false.
The values are compared case-insensitive.

For counting options the value must  be a integer value greater-equal to 0.
The value _does not_ increase the counter value by that amount, but sets the counter value to it.

[[OCB]]
== OPTION CALLBACK FUNCTIONS

If the variable name in the option definition has `()` appended, it in fact names a function to call when the option is found.
So:

   parseargs -o 'l:long#set_long()' -- -l

produces this line (among others):

    set_long 'true' || exit $?;

It calls the function `set_long` with the value `true` and exits the script if the function returns a non-zero return code.
The script exit code is the exit code of the function.

As long options for flags support setting it to false the value is given as a argument to the callback function.
Using

   parseargs -o 'l:long#set_long()' -- --long=false

would produce:

    set_long '' || exit $?;


IMPORTANT: Using callbacks disables duplicate and mutual exclusion checks of Parseargs.
Then this is the responsibility of the script author.

[[RQ]]
== REQUIRED OPTIONS

A option can be marked as required by prefixing the variable with a asterisk.

Example:

    l:long,o=*output_file

With this definition it is required to provide the option `-o`.
If it is not given, the script is exited with an error message.

[[MSO]]
== MODE SWITCH OPTIONS

A mode switch option is a extension of a simple flag.
It allows to set a single variable to different values, depending on the given option.

For the definition

    c#mode=copy,m#mode=move

The option `-c` would set the variable `mode` to "copy", while `-m` would set it to "move".

This definitions make the options `-c` and `-m` mutual exclusive.
Note that there is no mutual exclusion check, if callbacks are used!

If a mode switch option should be marked as required, it is sufficient to mark it in one of the definitions as required.

    c#*mode=copy,m#mode=move

== Supporting `--help` and `--version`

With the option `-h`, Parseargs supports the script option `--help` and calls the function `show_help`.
That function then displays a help text.

Similar with `-v`, Parseargs supports the script option `--version` and calls the function `show_version`.

Example usage:

    show_help()
    {
        echo "my-script [OPTIONS] [FILES]"
        echo "  Options"
        echo "   -d    produce debug output"
        echo
        echo "  FILES: files to process"
    }
    show_version()
    {
        echo "my-script v 1.0"
    }

    eval "$(parseargs -n my-script -hv -o 'd#debug' -- "$@")"

[[RP]]
== SINGLETON OPTIONS

A singleton option is a option that overwrites everything else on the command line and only the defined action for this option is executed.
A singleton option is defined by prefixing the variable name (or more typical function) with a `?`.
Typical usage of a singleton option is a custom help option. Like:

    help-details#?show_detailed_help()

If the option uses a callback function, the script is exited with the exit code 0 afterwards.

== PROGRAM ARGUMENTS

Program arguments are everything on the command line that is not an option (or its option-argument).
By default this arguments are stored as the positional parameter (`$1`, `$2` ...).

With the Parseargs option `-a` / `--arg-callback` a function can be named, that is used to report the program arguments.
In that case the positional parameter list is empty.

== HANDLING of `--`

The `--` is used to stop option processing and handle all following parts of the command line as program arguments.
AFAIK this is a POSIX requirement.

    parseargs -o 'l#long' -- -l -- -x

In this call the `-l` triggers setting the variable `long` to "true", but `-x` is handled as a program argument.
Without the `--` the `-x` would lead to an error due to unknown option.

**Supported with `bash`, `ksh` and `zsh`:**

Parseargs is also able to separate the program arguments given before or after a `--`.
With the command line option `-r ARRAY_NAME` / `--remainder=ARRAY_NAME`, the arguments behind a `--` are collected in the named array, while the arguments before it are provided as positional parameter.

With

    parseargs -r crew  -- Kirk -- Spock Bones

the value of `$1` is "Kirk", while "Spock" and "Bones" are available as `${crew[0]}` and `${crew[1]}`.

NOTE: This special handling might collide with the previous description of `--`.

== CALLBACK FUNCTIONS

Callback functions are used for

1. <<OCB, *OPTION CALLBACK FUNCTIONS*>>
2. `-a` / `--arg-callback`
3. `-e` / `--error-callback`

When any of this callbacks are used, Parseargs first generates code to verify that the named function actually exist.
If a required function is missing a error message is printed and the script is terminated with exit code 127.
This error should only occur during script development.

The code generated for calling a callback function checks the return code of the function and will exit the script immediately with the same exit code.

== SHELL SUPPORT

Parseargs can generate shell code for different shells.
By default code for `bash` is created.

The target shell can be changed with the option `-s` / `--shell`-

`-s sh`::
This generates code for a simple POSIX shell.
Those shells don't support local variables and array variable.
Due to this the option `-l` / `--local-vars` and `-r` / `--remainder` are not supported.

`-s bash`, `-s ksh` and `-s zsh`::
With this shells all features of Parseargs are supported.
The generated code for this shells is (as of today) nearly identical.
Only assigning an empty array is different in ksh than in bash or zsh.

== EXIT STATUS

0::
Success

1::
Error while processing shell script options.

11::
Invalid Parseargs options or option definition.

== AUTHOR

Ralf Schandl

Project home is https://github.com/rakus/parseargs.

== COPYING

Copyright (C) 2023 Ralf Schandl.

Free use of this software is granted under the terms of the MIT License.

This software is released WITHOUT ANY WARRANTY; without even the implied
warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

*USE AT YOUR OWN RISK!*

// vim:ft=asciidoc:et:ts=4:spelllang=en_us:spell
