
= Parseargs Tutorial
:author:    Ralf Schandl
:revnumber: {version}
:revdate:   {localdate}
:copyright-year: 2023
:doctype: article
:icons: font
:toc: left
:numbered:
// enable experimental for btn:[...].
//:experimental:

Parseargs is a command line option parser for shell scripts.

This tutorial explains the features of Parseargs using examples.

The first section <<POSIX>> treats all functionality that works in a POSIX compliant shell.
Also _zsh_ is not POSIX compliant (and never wanted to be), the mentioned features should run with it.

The second section <<EXTENDED>> handles those few features that need functionality beyond the POSIX standard.
Currently there is only on feature, that requires the support of array variables.
The shells _bash_, _ksh_ and _zsh_ provide this.
These shells can be enabled by using the option `-s` / `--shell` with the shell name.

NOTE: When _ksh_ is mentioned in this document, we are talking about _ksh92_ or newer.
Parseargs was never tested with _ksh88_.


[[POSIX]]
== POSIX Shells

=== Simple Usage

The following script should support two options and arguments.
The options are:

* `-l`  to enable "long" output.
* `-o <filename>` to define a file to write to

.Script `example.sh`
[%nowrap,source,bash]
----
include::examples/example.sh[]
----

Before testing lets look at the options and arguments given to Parseargs.

`-n example.sh`::
This tells Parseargs the name of the calling script.
The name is used as prefix for error messages.

`-o 'l#long_output,o=outfile'`::
This defines two options, separated by a comma.

`l#long_output`:::
This definition defines a simple flag.
The `\#` in the middle is the marker for a flag.
The part before defines the option character.
Here `l` defines the option `-l`.
The part after the `#` is the variable that should be set, when `-l` was found on the command line. The variable gets the value "true" assigned.

`o=outfile`:::
This definition defines a assignment option.
A assignment option needs an additional argument.
The `=` in the middle is the marker for a assignment.
Again the part before defines the option.
Here `-o`.
The part after the marker is the name of the variable.
This variable gets the option argument assigned.

`--`::
The double dash separates the Parseargs options from the shell script options.

`"$@"`::
This is replaced by the script options.
Always use exactly this notation.
A simple `$@` (without the quotes) or `$*` might fail.
See your shell documentation.

[IMPORTANT]
====
The option character may be any ASCII character, except for `-` (minus), whitespace or control characters.

The characters `#`, `%`, `+`, `:`, `=`, `\` and `,` have to be escaped with a backslash.
====

The trailing `|| exit 1` is just a safety net, in case something goes wrong during eval.

Let's test the script:

[%nowrap]
----
$ ./example.sh -l -o out.file in.file other.file
Long output is enabled
Output file: 'out.file'
Arguments: in.file other.file
----

No space needed between `-o` and the file name:

[%nowrap]
----
$ ./example.sh -l -oout.file in.file other.file
Long output is enabled
Output file: 'out.file'
Arguments: in.file other.file
----

And `-l` and `-o` can be combined into one:

[%nowrap]
----
$ ./example.sh -loout.file in.file other.file
Long output is enabled
Output file: 'out.file'
Arguments: in.file other.file
----

Options and argument order is not relevant:

[%nowrap]
----
$ ./example.sh -l in.file other.file -oout.file
Long output is enabled
Output file: 'out.file'
Arguments: in.file other.file
----

Using a unknown option:

[%nowrap]
----
$ ./example.sh -X
example.sh: Unknown option: '-X'
----

Duplicate options are not allowed:

[%nowrap]
----
$ ./example.sh -o out.file -o other-out.file  in.file
example.sh: Duplicate option: '-o'

$ ./example.sh -l -l -o out.file  in.file
example.sh: Duplicate option: '-l'
----

.How does this work?
****
To understand how Parseargs works, it can simply be called from the command line.

[%nowrap]
----
$ parseargs -n example.sh -o 'l#long_output,o=outfile' -- -l -o out.file in.file other.file
long_output='true';
outfile='out.file';
set -- 'in.file' 'other.file'
----

First the potentially used variables are defined.
As `-l` is given, the variable assignment `long_output='true'` is generated.
And due to `-o out.file` the assignment `outfile='out.file` is added.
Finally with `set -- ...` the positional parameter (`$1`, `$2` ...) are assigned.

Here is what happens, when an unknown option is found:

[%nowrap]
----
$ parseargs -n example.sh -o 'l#long_output,o=outfile' -- -X
example.sh: Unknown option: -X
exit 1
----

The error message "example.sh: Unknown option: -X" is written to STDERR.

Or here the argument for the option -o is missing:

[%nowrap]
----
$ parseargs -n example.sh -o 'l#long_output,o=outfile' -- -o
example.sh: Missing argument for: -o
exit 1
----

Note that the error messages are printed to STDERR by parseargs.
Only `exit 1;` is printed to STDOUT and hence evaluated by `eval` when used in a script.

Just play around with Parseargs.
Use arguments with spaces or special character.
****

=== Long Options

A lot of programs support additional long forms of options.
Like `-l` and `--long`.
Parseargs also supports this:

.Script `long-opt.sh`
[%nowrap,source,bash]
----
include::examples/long-opt.sh[]
----

Now we have two colon-separated options before the type marker (`#`, `=`).
If a option is a single character, it defines a short option (`l` -> `-l`).
With multiple characters it is a long option, that has two leading dashes (`long` -> `--long`).

[IMPORTANT]
====
Long options may contain any ASCII character, except for  `=`, whitespace or control characters. The `-` (minus) is not allowed as the first character.

The characters `#`, `%`, `+`, `:`, `\` and `,` have to be escaped with a backslash.
====

Now our example script enables long output by either using `-l` or `--long` and the output file can be set with `-o out.file` or `--out-file out.file` or even `--out-file=out.file`.

Again some tests:

[%nowrap]
----
$ ./long-opt.sh --long --out-file out.file in.file other.file
Long output is enabled
Output file: 'out.file'
Arguments: in.file other.file

$ ./long-opt.sh --long --out-file=out.file in.file other.file
Long output is enabled
Output file: 'out.file'
Arguments: in.file other.file
----

Duplicate option detection still works:

----
$ ./long-opt.sh --long -l
long-opt.sh: Duplicate option: '-l/--long'
----

*Long Options and Optional Arguments*

With long options an optional argument is supported for flag options.
This optional argument is directly appended to the option with a `=`.
The values `true` and `yes` are interpreted as boolean true and `false` and `no` as false.
The check is case insensitive.

So, to reuse the example above:

[%nowrap]
----
$ ./long-opt.sh --long=true --out-file=out.file in.file
Long output is enabled
Output file: 'out.file'
Arguments: in.file

$ ./long-opt.sh --long=yes --out-file=out.file in.file
Long output is enabled
Output file: 'out.file'
Arguments: in.file

$ ./long-opt.sh --long=false --out-file=out.file in.file
Output file: 'out.file'
Arguments: in.file

$ ./long-opt.sh --long=no --out-file=out.file in.file
Output file: 'out.file'
Arguments: in.file

$ ./long-opt.sh --long=anything --out-file=out.file in.file
long-opt.sh: Invalid boolean value: 'anything'
----

.By the Way ....
****
It is possible to define multiple short and long options.

[%nowrap,source,bash]
----
eval "$(parseargs -n long-opt.sh -o 'l:long:D:detailed#long_output,...' -- "$@")" || exit 1
----

Now `-l`, `--long`, `-D` and `--detailed` all would enable long output.
I don't know how useful this is, but it is possible.
****

=== Counting Options

Tools sometimes have an option to increase verbosity of the output.
Example from the ssh man page:

[%nowrap]
----
-v      Verbose mode.  Causes ssh to print debugging messages about its
        progress.  This is helpful in debugging connection, authentica‐
        tion, and configuration problems.  Multiple -v options increase
        the verbosity.  The maximum is 3.
----

Parseargs has an own option type to support this.
A "Counting Option" is defined using the marker `+`.

The following script only supports the options `-v` and `--verbose`.

.Script `verbosity.sh`
[%nowrap,source,bash]
----
include::examples/verbosity.sh[]
----


[%nowrap]
----
$ ./verbosity.sh
Verbosity: 0

$ ./verbosity.sh -v
Verbosity: 1

$ ./verbosity.sh -vvv
Verbosity: 3

$ ./verbosity.sh -vvvvvvv
Verbosity: 7
----

The long option form additionally supports a optional argument:

[%nowrap]
----
$ ./verbosity.sh --verbose
Verbosity: 1

$ ./verbosity.sh --verbose -v
Verbosity: 2

$ ./verbosity.sh --verbose=5
Verbosity: 5

$ ./verbosity.sh --verbose=full
verbosity.sh: Not a valid count value: "full"
----

IMPORTANT: The long form with optional argument sets the verbosity, it does not increase it by the given number.

[%nowrap]
----
$ ./verbosity.sh -vv --verbose=5
Verbosity: 5
----

=== Mode Switch Options

A Mode Switch Options are not a new option type, but a extension of a simple flag.
Mode switches use one variable with different options and assign different values to the variable.

A simple example would be whether something should be copied or moved.
In that case the option `-c` would request to copy and `-m` would request move.

The definition of such options look like normal flags, but have a equal sign and a value appended.

.Script `mode-switch.sh`
[%nowrap,source,bash]
----
include::examples/mode-switch.sh[]
----

And here some tests:

[%nowrap]
----
$ ./mode-switch.sh -c
Mode: copy

$ ./mode-switch.sh -m
Mode: move

$ ./mode-switch.sh -cm
mode-switch.sh: Options are mutual exclusive: -c/--copy, -m/--move
----

=== Required Options

Sometimes a option might be required. Parseargs supports this with a asterisk before the variable name.

.Script `required.sh`
[%nowrap,source,bash]
----
include::examples/required.sh[]
----

And now a test:

[%nowrap]
----
$ ./required.sh -o output.file
Output file: output.file

$ ./required.sh
required.sh: Required option not found: -o
----


=== Showing Help and Version

First up: Parseargs itself does not support creating help texts.
But Parseargs can call a existing shell function that prints some help text.

With the Parseargs option `-h` / `--help-opt`, the script option `--help` is supported.
If the option is given, the shell function `show_help` is called and the script is terminated with exit code 0.

To display the script version, the Parseargs option `-v` / `--version-opt` enables support for the script option `--version`.
If the option is given, the shell function `show_version` is called and the script is terminated with exit code 0.

The script must define the named `show_*` functions.
If they are not defined, a error message is displayed and the script is terminated.

.Script `help.sh`
[%nowrap,source,bash]
----
include::examples/help.sh[]
----

Displaying help and version:

[%nowrap]
----
$ ./help.sh --help
Usage: example.sh OPTIONS <input-file...>
  -l, --long           enable detailed output
  -o, --out-file FILE  file to write result

$ ./help.sh --version
help.sh 1.0
----

To better understand how this works, see the sections <<CALLBACKS>> and <<SINGLETON_OPTS>>.


[[CALLBACKS]]
=== Using Callbacks

Till now we used Parseargs to assign variables for the options found on the command line, but it is also able to work with shell functions.

When using functions, Parseargs also generates code to test for the existence of the function.
Assuming a function `set_out_file` should be used, it is always checked whether this function exists.

[%nowrap,source,bash]
----
# default
if ! LC_ALL=C command -V set_out_file 2>/dev/null | head -n1 | grep function >/dev/null; then echo >&2 "ERROR: Function 'set_out_file' does not exist."; exit 127; fi;

# with --shell bash, ksh or zsh
if ! typeset -f set_out_file >/dev/null 2>&1; then echo >&2 "ERROR: Function 'set_out_file' does not exist."; exit 127; fi;
----

This code will exit the calling script if the function does not exist.
The check is always done, whether the function is needed in the actually generated code or not.

When calling the callback the exit status of the function must be zero else the calling script is terminated with function exit code.
The code for this looks like this:

[%nowrap,source,bash]
----
set_out_file 'output.file' || exit $?
----

==== Callbacks for Options

Instead of assigning variables for options, it is also possible to call a function.
By adding `()` to the name, it defines the function to call.

.Script `option-cb.sh`
[%nowrap,source,bash]
----
include::examples/option-cb.sh[]
----

Testing:

[%nowrap]
----
$ ./option-cb.sh -v -l -o out.file -vv input
set_verbosity(1)
set_long(true)
set_outfile(out.file)
set_verbosity(3)
Arguments: input

$ ./option-cb.sh --long=false input
set_long()
Arguments: input
----

* For counting options, the callback might be called multiple times with the current count value.
* For flags it is called with a value `'true'`.
  If the option explicitly is set to `false` using `--option=false`, the callback is called with an empty string.
* For assignment options the callback is called with the option argument.

[WARNING]
====
Using a callback disables checks within Parseargs.

The duplicate usage of options is not checked and also the duplicate usage of mode-switch options are not detected.

With callbacks you have more control and possibilities, but also more responsibilities.
====

==== Callback for Arguments

In the previous sections we have seen callbacks for options, this is also possible for program arguments.

The callback for program arguments is defined with the Parseargs option `-a` or `--arg-callback`.

.Script `args-cb.sh`
[%nowrap,source,bash]
----
include::examples/args-cb.sh[]
----

When the argument callback is used, the positional parameters are always empty.
So `$1` etc are unset.

==== Callback on Error

Parseargs allows the defition of an error callback.
This defines a function that is called before Parseargs emits `exit 1` to terminate the calling script.

The following example doesn't support any options and insults you when you give one.

.Script `error-cb.sh`
[%nowrap,source,bash]
----
include::examples/error-cb.sh[]
----

[%nowrap]
----
$ ./error-cb.sh
OK

$ ./error-cb.sh -x
error-cb.sh: Unknown option: -x
You did something stupid!
$
----


=== A Script without Options

Parseargs if even useful in scripts that don't support any options.
In that use case it would output an error message when a option is given.

.Script `no-opt.sh`
[%nowrap,source,bash]
----
include::examples/no-opt.sh[]
----

In this script we also use the option `-p` / `--posix`, then Parseargs stops looking for options as soon as the first program argument is found.

[%nowrap]
----
$ ./no-opt.sh first second
Arguments: first second

$ ./no-opt.sh -X first second
no-opt.sh: Unknown option: -X

$ ./no-opt.sh  first second -X
Arguments: first second -X
----


=== The Option Argument Separator '--'

POSIX defines the `--` as a separator between options and program arguments.

Reusing our first script `example.sh`:

[%nowrap]
----
$ ./example.sh -o out.file -X
example.sh: Unknown option: -X

$ ./example.sh -o out.file -- -X
Output file: 'out.file'
Arguments: -X
----

A second `--` is handled as a normal argument:

[%nowrap]
----
$ ./example.sh  -o out.file -- -X -- test
Output file: 'out.file'
Arguments: -X -- test
----


=== Initializing Variables

With the option `-i` / `--init-vars` the variables can be initialized with their default values.
Note, that variables of counting options are always initialized to 0.
This is useful, when the script runs with `set -u` to treat unset variables as error.

Note that this is for variables only. Callbacks are not called.

[%nowrap]
----
$ parseargs -n example.sh -o 'l#long,o=outfile,v+verbosity' --init-vars -- -o out.file -l
long='';
outfile='';
verbosity=0;
outfile='out.file';
long='true';
set --
----

[[SINGLETON_OPTS]]
=== Singleton Options

A Singleton Option is an option that supersede all other options or arguments on the command line.
The typical use for this is a help option.
In fact the support for `--help` is implemented using this.

A option is marked as a by putting a `?` in front of the function name (variables are rarely used here).
The following is used to support `--help`

[%nowrap]
----
help#?show_help()
----

The `?` tells Parseargs that this is a singleton option and that

* only this option should be processed.
* all other content of the command line should be dropped. (The content before the `--help` must still be valid.)
* the calling script should be terminated with exit code 0 if the target is a callback.

So this can be easily used to implement additional help options.
Maybe `--help-storage#?show_help_storage()`.

This feature can also be used for other things.
The following is from a script that is used as an unpacker for arbitrary archives.

[%nowrap,source,bash]
----
eval "$(parseargs -hin ERROR -o "l#mode=listMode,L#mode=topLevelList,D#mode=basenameDir,S#mode=singleDir,T#?checkPrograms(),d=tgtDir,v+verbose" -- "$@")" || exit 1
----

The interesting part is `T#?checkPrograms()`.
This defines the option `-T` as a singleton option, that calls the function `checkPrograms`.
In the actual script the `-T` triggers a test whether the needed tools are available and hence which archive types are supported.
After this test is completed, the script is terminated.
No other actions is performed, independent of other options given on the command line.


[[EXTENDED]]
== Extended Shells

This section describes functionalities, that need additional capabilities beyond those defined by POSIX.

=== Separating Arguments behind a `--`

IMPORTANT: Only supported with shells `bash`, `ksh` or `zsh`.

Sometimes it is useful to handle the arguments before and after a `--` differently.

The following command monitors the file `tutorial.adoc` and executes the command `make html` as soon as a change is detected.

[%nowrap]
----
$ when-changed tutorial.adoc -- make html
----

Here the arguments before the `--` are different than the arguments behind it.

Parseargs is able to collect the arguments behind the `--` in a shell array and leave the arguments before it as positional parameter (`$1`...).
The option `-r` / `--remainder` is used to define the name of the array.

The Parseargs call for this would look like this:

[%nowrap,source,bash]
----
eval "$(parseargs -s bash --remainder cmd -h -- "$@")" || exit 1
----

Assuming the call above, the name `tutorial.adoc` would be available as `$1` and the words `make` and `html` as `${cmd[0]}` and `$cmd[1]}`.

Note that in _zsh_ it would be `${cmd[1]}` and `$cmd[2]}`, as arrays in _zsh_ are 1-based.


== Details

=== Support for Different Shells

Parseargs supports generating code for different shells. The following shells are supported:

`--shell=sh` (the default)::
With this setting, code for a POSIX compliant shell is generated.
This should work with any POSIX compliant shell and with _zsh_.
The option `-r` / `--remainder` is not supported.

`--shell=bash`, `--shell=ksh` and `--shell=zsh`::
This shells support all features of Parseargs.
The code generated is (as of today) identical, except for array initialization, which is different in _ksh_.


=== Parseargs and ShellCheck

https://github.com/koalaman/shellcheck[ShellCheck] is a static code analysis
tool for shell scripts.
If you don't use it yet, you really should.

As Parseargs is creating and assigning new variables at runtime, ShellCheck can't know about them and will complain.
For our first example the following output would be created:

[%nowrap]
----
$ shellcheck ./example.sh

In example.sh line 8:
echo "Output file: '$outfile'"
                    ^------^ SC2154 (warning): outfile is referenced but not assigned.

For more information:
  https://www.shellcheck.net/wiki/SC2154 -- outfile is referenced but not ass...
----

The best solution is to initialize default values before calling Parseargs.

Like:

[%nowrap,source,bash]
----
#!/bin/sh

long_output=
outfile=
eval "$(parseargs -n example.sh -o 'l#long_output,o=outfile' -- "$@")" || exit 1
----



=== Parseargs and Invalid UTF-8

As of today, Parseargs can only handle arguments that are valid UTF-8.

If a invalid UTF-8 character is found, Parseargs will display an error message and exit the calling script.


// vim:ft=asciidoc:et:ts=4:spelllang=en_us:spell
